<?xml version="1.0"?>
<!DOCTYPE PRODUCTION_ORDERS [
<!ELEMENT ORDERS (Request_Stores | Order*)>
<!ELEMENT Request_Stores EMPTY>
<!ELEMENT Order (Transform | Unload)>
<!ATTLIST Order
          Number   (CDATA) #REQUIRED
>
<!ELEMENT Transform EMPTY>
<!ATTLIST Transform
          From     (CDATA) #REQUIRED
          To       (CDATA) #REQUIRED
          Quantity (CDATA) #REQUIRED
          MaxDelay (CDATA) #REQUIRED
>
<!ELEMENT Unload EMPTY>
<!ATTLIST Unload
          Type        (CDATA) #REQUIRED
          Destination (CDATA) #REQUIRED
          Quantity    (CDATA) #REQUIRED
>
]>
<ORDERS>
<Order Number="009">
<Unload Type="P2" Destination="D2" Quantity="8"/>
</Order>
<Order Number="010">
<Unload Type="P7" Destination="D3" Quantity="2"/>
</Order>
<Order Number="011">
<Unload Type="P8" Destination="D3" Quantity="2"/>
</Order>
<Order Number="012">
<Unload Type="P5" Destination="D1" Quantity="8"/>
</Order>
<Order Number="013">
<Unload Type="P3" Destination="D3" Quantity="4"/>
</Order>
</ORDERS>

