<?xml version="1.0"?>
<!DOCTYPE PRODUCTION_ORDERS [
<!ELEMENT ORDERS (Request_Stores | Order*)>
<!ELEMENT Request_Stores EMPTY>
<!ELEMENT Order (Transform | Unload)>
<!ATTLIST Order
          Number   (CDATA) #REQUIRED
>
<!ELEMENT Transform EMPTY>
<!ATTLIST Transform
          From     (CDATA) #REQUIRED
          To       (CDATA) #REQUIRED
          Quantity (CDATA) #REQUIRED
          MaxDelay (CDATA) #REQUIRED
>
<!ELEMENT Unload EMPTY>
<!ATTLIST Unload
          Type        (CDATA) #REQUIRED
          Destination (CDATA) #REQUIRED
          Quantity    (CDATA) #REQUIRED
>
]>
<ORDERS>
<Order Number="001">
<Transform From="P1" To="P3" Quantity="3" MaxDelay="60"/>
</Order>
<Order Number="002">
<Transform From="P3" To="P5" Quantity="7" MaxDelay="60"/>
</Order>
<Order Number="003">
<Transform From="P4" To="P5" Quantity="6" MaxDelay="60"/>
</Order>
<Order Number="004">
<Transform From="P1" To="P9" Quantity="20" MaxDelay="60"/>
</Order>
<Order Number="005">
<Transform From="P1" To="P4" Quantity="10" MaxDelay="60"/>
</Order>
</ORDERS>
